# @backend_HostAddress = http://localhost:5204
@backend_HostAddress = http://localhost:8080

POST {{backend_HostAddress}}/profiles/
Content-Type: application/json

{
    "Description": "Experienced software developer",
    "SkillsHave": "C#, .NET, JavaScript",
    "SoftwaresUsed": "Visual Studio, Git",
    "JobRole": "Full Stack Developer",
    "RoleResponsibility": "Developing and maintaining web applications",
    "OfficeVenue": "Remote",
    "MasteryLevel": "Expert",
    "WorkingExperience": 5.5,
    "JoinedDate": "2020-01-15",
    "CompanyName": "Tech Solutions Inc.",
    "Projects": "Project A, Project B",
    "ProjectReference": "https://myProjectA.com, https://myProjectB.com"
}

###
GET {{backend_HostAddress}}/profiles/

###
DELETE  {{backend_HostAddress}}/profiles/7